Feature: 适配多机器人账号连接复用
nonebot/adapter-onebot pull request #34
Opened 2022-11-13 16:28 UTC by he0119

不知道 Event 的命名是不是直接用 Self 和 Status 比较好。

2022-11-15 09:16 UTC, yanyongyu commented on nonebot/adapters/onebot/v12/adapter.py
> +                    self._handle_status_update(event)
这里为啥不处理meta event，meta event也要广播，status update在之前单独处理就行了

2022-11-15 09:16 UTC, yanyongyu commented on nonebot/adapters/onebot/v12/adapter.py
> +                            self._handle_status_update(event, bots, websocket)
这边写的两个if干啥

2022-11-15 09:16 UTC, yanyongyu commented on nonebot/adapters/onebot/v12/adapter.py
> +                        event = cast(MessageEvent, event)
这里cast不对，最好搞一个新的基类

2022-11-15 09:16 UTC, yanyongyu commented on nonebot/adapters/onebot/v12/adapter.py
> +        self.platforms: Dict[str, str] = {}
这里最好用`dict[str, tuple[WebSocket, str]]`的形式来确保一对一一定存在

2022-11-15 09:16 UTC, yanyongyu commented on nonebot/adapters/onebot/v12/adapter.py
> +                            self._handle_status_update(event, bots, websocket)
这里正确在bot离线的时候从bots里删除了吗

2022-11-15 09:16 UTC, yanyongyu commented on nonebot/adapters/onebot/v12/adapter.py
> +                            if not impl and raw_data.get("echo") == "get_version":
不要把第一次处理混在while循环里

2022-11-15 09:16 UTC, yanyongyu commented on nonebot/adapters/onebot/v12/adapter.py
> +                        bots = {}
```suggestion
                        bots.clear()
```

2022-11-15 09:22 UTC, he0119 commented on nonebot/adapters/onebot/v12/adapter.py
> +                    self._handle_status_update(event)
哦哦，我以为只需要适配器处理🤣

2022-11-15 09:23 UTC, he0119 commented on nonebot/adapters/onebot/v12/adapter.py
> +                            self._handle_status_update(event, bots, websocket)
这个应该是排除掉心跳，没有处理它。

2022-11-15 09:24 UTC, he0119 commented on nonebot/adapters/onebot/v12/adapter.py
> +                        event = cast(MessageEvent, event)
该叫什么好呢，SelfEvent？

2022-11-15 09:25 UTC, he0119 commented on nonebot/adapters/onebot/v12/adapter.py
> +        self.platforms: Dict[str, str] = {}
确实，我当时是因为 HTTP WebHook 也需要这个 platforms 所以就写一起了。

2022-11-15 09:29 UTC, he0119 commented on nonebot/adapters/onebot/v12/adapter.py
> +                            if not impl and raw_data.get("echo") == "get_version":
这个该怎么搞好？因为连接上之后，实现端也会发送比如 status_update，甚至 event 过来。get_version 的返回结果不一定是第一个。

2022-11-15 11:20 UTC, he0119 commented on nonebot/adapters/onebot/v12/adapter.py
> +                            self._handle_status_update(event, bots, websocket)
我传递进去删除了。

2022-12-17 06:15 UTC, yanyongyu requested changes

2022-12-17 06:15 UTC, yanyongyu commented on nonebot/adapters/onebot/v12/adapter.py
> +                                impl = event.version.impl
这部分等待加个log吧，不然都不知道适配器在什么状态

2022-12-17 12:08 UTC, yanyongyu approved these changes

2022-12-17 12:24 UTC, merged