Feature: 优化消息和消息段的`repr()`显示效果
nonebot/adapter-onebot pull request #44
Opened 2023-01-08 15:41 UTC by mnixry

包含以下改进:

- 在`MessageSegment`的param过长时进行truncate, 防止日志刷屏
- 对`text`类型的`MessageSegment`使用`repr()`展示, 防止换行过多刷屏和扰乱日志输出
- 不再展示任何类似CQ码的内容 ~~, 防止天才用户看到就想用正则~~

2023-01-08 15:54 UTC, yanyongyu requested changes
还需要改一下message event的description，truncate方法写到utils里

2023-01-08 15:56 UTC, yanyongyu commented on nonebot/adapters/onebot/v11/message.py
> +            return "".join(text_repr)
这里为啥不写成[1:-1]啊喂

2023-01-08 15:56 UTC, yanyongyu commented on nonebot/adapters/onebot/v11/message.py
> +        return "".join([repr(seg) for seg in self])
这里的方括号去掉

2023-01-11 11:46 UTC, mnixry commented on nonebot/adapters/onebot/v11/message.py
> +            return "".join(text_repr)
> 这里为啥不写成[1:-1]啊喂

~~因为我觉得丑~~

2023-01-11 12:01 UTC, yanyongyu commented on nonebot/adapters/onebot/v11/message.py
> +            return "".join(text_repr)
你这样拆分拼接字符串不是浪费时间，还是python最慢的拼接字符串

2023-01-12 02:46 UTC, yanyongyu requested changes

2023-01-12 02:46 UTC, yanyongyu commented on nonebot/adapters/onebot/v11/message.py
> +            [f"{k}={truncate(v)}" for k, v in data.items() if v is not None]
```suggestion
            [f"{k}={truncate(str(v))}" for k, v in data.items() if v is not None]
```

2023-01-12 02:46 UTC, yanyongyu commented on nonebot/adapters/onebot/v11/message.py
> +        data = self.data.copy()
data不用copy吧，又不修改只读

2023-01-12 02:46 UTC, yanyongyu commented on nonebot/adapters/onebot/v11/message.py
>          data = self.data.copy()
看上去这里也不用copy，当时为啥写了copy

2023-01-12 02:46 UTC, yanyongyu commented on nonebot/adapters/onebot/v11/utils.py
> +    result = s[: length - len(end)].rsplit(" ", 1)[0]
```suggestion
    result = s[: length - len(end)].rsplit(maxsplit=1)[0]
```

2023-01-12 05:21 UTC, yanyongyu approved these changes

2023-01-12 05:21 UTC, merged